import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/db";

/**
 * Initialize GitHub repo for a project
 * Creates a new GitHub repository with the specified name
 */
export async function POST(req: Request) {
  const session = await auth();
  const userId = (session as { userId?: string }).userId;
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: { projectId?: string; repoName?: string; githubToken?: string } = {};
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const { projectId, repoName, githubToken } = body;
  
  if (!projectId || !repoName || !githubToken) {
    return NextResponse.json({ 
      error: "projectId, repoName, and githubToken required" 
    }, { status: 400 });
  }

  // Verify project ownership
  const project = await prisma.project.findUnique({
    where: { id: projectId, userId },
  });

  if (!project) {
    return NextResponse.json({ 
      error: "Project not found or forbidden" 
    }, { status: 403 });
  }

  try {
    // Create GitHub repo using GitHub API
    const response = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${githubToken}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        name: repoName,
        description: `Generated by Vibe - ${project.name}`,
        private: false,
        auto_init: true, // Initialize with README
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      return NextResponse.json({ 
        error: "Failed to create GitHub repo",
        detail: error.message || "Unknown error"
      }, { status: response.status });
    }

    const repoData = await response.json();

    // Update project with GitHub info
    await prisma.project.update({
      where: { id: projectId },
      data: {
        githubRepoName: repoName,
        githubRepoUrl: repoData.html_url,
        githubEnabled: true,
      },
    });

    return NextResponse.json({
      success: true,
      repoUrl: repoData.html_url,
      repoName: repoName,
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    return NextResponse.json({ 
      error: "Failed to initialize GitHub repo", 
      detail: message 
    }, { status: 500 });
  }
}
